# If you only want the circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too
#
aliases:
 - &filter-only-master
   branches:
     only:
       - master

version: 2
jobs:
  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "lealarcon@users.noreply.github.com"
            git config --global user.name "lealarcon"
            echo "machine github.com login lealarcon password $GITHUB_TOKEN" > ~/.netrc
            git checkout -B gh-pages
            git reset --hard origin/master
            yarn install && GIT_USER=lealarcon &&  yarn run build
            ls -ls
            git add -f build && git commit -m $CIRCLE_BUILD_NUM
            git push origin `git subtree split --prefix build master`:gh-pages --force	
            git subtree push --prefix build origin gh-pages


            

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
         filters: *filter-only-master
