--- 
    aliases: 
      - 
        branches: 
          only: 
            - master
    jobs: 
      deploy-website: 
        docker: 
          - 
            image: "circleci/node:10"
        steps: 
          - checkout
          - 
            run: 
              command: |
                  git config --global user.email "lealarcon@users.noreply.github.com"
                  git config --global user.name "lealarcon"
                  echo "machine github.com login lealarcon password $GITHUB_TOKEN" > ~/.netrc
                  git checkout -B gh-pages
                  git reset --hard origin/master
                  yarn install && GIT_USER=lealarcon &&  yarn run build
                  ls -ls
                  git add -f build && git commit -m $CIRCLE_BUILD_NUM
                  git push origin `git subtree split --prefix build master`:gh-pages --force	
                  git subtree push --prefix build origin gh-pages
              name: "Deploying to GitHub Pages"
    version: 2
    workflows: 
      build_and_deploy: 
        jobs: 
          - 
            deploy-website: 
              filters: 
                branches: 
                  only: 
                    - master
      version: 2
    